# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	git
	autojump
	colored-man-pages
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# be able to use ctrl + backspace / crtl + delete to delete entire word
bindkey '5~' kill-word
bindkey '^H' backward-kill-word
# be able to use ctrl + left / ctrl + right to move word by word
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

export GIT_EDITOR="vim"

export PATH="$HOME/.cargo/bin:$PATH"

export MAIL="msloot@student.42.fr"

alias nor="norminette"
alias norm="norminette"

alias clangW="clang -Wall -Werror -Wextra"

alias gc="git commit --message"
alias gst="git status --short"
alias gtree="git log --graph --oneline --decorate"

git config --global alias.vommit "commit"

alias sl="ls"
alias mk="make"
alias amke="make"
alias mkae="make"
alias maek="make"
alias ivm="vim"
alias vmi="vim"
alias gti="git"

alias bringz="git pull"
alias byes="exit"
alias chicken="git add"
alias donotwant="rm"
alias dowant="cp"
alias gimmeh="touch"
alias gimme="touch"
alias moar="more"
alias nomnom="killall"
alias rtfm="man"
alias tldr="less"

alias s="sudo"

alias up="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y"

alias ll="ls -lah"
unalias l # remove zsh alias
function l() {
	exa --long --all --no-permissions --no-filesize --no-user --no-time --git --icons "$@" 2>/dev/null || ls -lah "$@"
}

function lr() {
	exa --git-ignore --ignore-glob='.git' --recurse --group-directories-first --long --all --no-permissions --no-filesize --no-user --no-time --git --icons "$@" 2>/dev/null || ls -lahR "$@"
}

function lt() {
	exa --git-ignore --ignore-glob='.git' --tree --group-directories-first --long --all --no-permissions --no-filesize --no-user --no-time --git --icons "$@" 2>/dev/null || ls -lahR "$@"
}

function chrono() {
	if [[ $# -eq 1 ]]; then
		printf $(($(date -u +%s.%N) - $1))
	elif [[ $# -eq 2 ]]; then
		printf $(($2 - $1))
	elif [[ $# -eq 0 ]]; then
		printf $(date -u +%s.%N)
	else
		echo -e "usage: \033[1m$0\033[0m              \treturn current UTC time
		\033[1m$0 \033[35m<start>\033[0m      \treturn elapsed time since \033[1;35m<start>\033[0m
		\033[1m$0 \033[35m<start> <end>\033[0m\treturn elapsed time between \033[1;35m<start>\033[0m and \033[1;35m<end>\033[0m"
		return 1
	fi
	return 0
}

function rmbk() {
	local CMD='find . -type d \( -name ".git*" -o -path "./target" -o -name "node_modules" \) -prune -o -type f -name "*~"'

	if [[ $# -lt 1 ]]; then
		local start="$(chrono)"

		local n="$(eval $CMD -print -exec rm -f {} + | wc -l)"

		local elapsed="$(chrono "$start")"

		printf "\033[1;32m$n\033[0m in \033[1;32m%.0f\033[0m\033[32mms\033[0m\n" "$((elapsed * 1000))"

		return 0
	fi

	local HELP="usage: \033[1m$0 \033[35m[option]\033[0m
option:
	\033[1m-h\033[0m, \033[1m--help\033[0m\tshow this help message and exit
	\033[1m-p\033[0m, \033[1m--print\033[0m\tprint found files
	\033[1m-s\033[0m, \033[1m--show\033[0m\tdelete found files and print them"

	if [[ $1 == "-h" || $1 == "--help" ]]; then
		echo -e $HELP
		return 0
	elif [[ $1 == "-p" || $1 == "--print" ]]; then
		eval $CMD -print
	elif [[ $1 == "-s" || $1 == "--show" ]]; then
		eval $CMD -print -exec rm -f {} +
	else
		echo -e "unknown option:\t\033[1;33m$1\033[0m"
		echo -e $HELP
		return 1
	fi
}

unalias ga # remove git plugin alias
function ga() {
	if [[ $# -eq 0 ]]; then
		git add --all
	else
		git add "$@"
	fi
	git status --short
	echo -e "\n\033[3mun-add:\033[0m\t\033[1;38;2;232;77;49mgit\033[39m restore \033[2m--staged\033[0m \033[1;35m<path>\033[0m\n\033[3m    or:\033[0m\t\033[1;38;2;232;77;49mg\033[39mr\033[2ms \033[35m[path]\033[0m"
}

unalias grs # remove git plugin alias
function grs() {
	if [[ $# -eq 0 ]]; then
		git restore --staged .
	else
		git restore --staged "$@"
	fi
	git status --short
}

function gy() {
	if [[ $# -ne 1 ]]; then
		echo -e "usage: \033[1m$0 \033[35m<commit_message>\033[0m"
		return 1
	fi

	git status --short
	git add --all
	git status --short
	git commit --message "$1"
	git push --quiet
}

function gt() {
	if [[ $# -ne 1 ]]; then
		echo -e "usage: \033[1m$0 \033[35m<commit_message>\033[0m"
		return 1
	fi

	git status --short
	git add --all
	git status --short
	git commit --message "$1"
}

function gpn() {
	if [[ $# -lt 1 ]]; then
		echo -e "usage: \033[1m$0 \033[35m<file1> <file2> <...>\033[0m"
		return 1
	fi

	local commit=""

	local file
	for file in "$@"; do
		git add "$file"
		commit+="\`$file\` "
	done

	git commit --message "$commit"
	git push --quiet
}

function gmc() {
	if [[ $# -lt 1 ]]; then
		echo -e "usage: \033[1m$0 \033[35m<branch1> <branch2> <...>\033[0m"
		return 1
	fi

	local base_branch="$(git branch --show-current)"

	local current="$base_branch"
	local b
	for b in "$@"; do
		echo -e "\033[1;35m$b\033[0m"
		git checkout "$b" --quiet || return 1
		git pull --quiet || return 1
		git merge "$current" --quiet || return 1
		git push --quiet || return 1
		current="$b"
	done

	git checkout "$base_branch" --quiet || return 1
	git merge "$current" --quiet || return 1
	git push --quiet || return 1
}
